import { MigrationInterface, QueryRunner } from "typeorm";

export class  $npmConfigName1746875099859 implements MigrationInterface {
    name = ' $npmConfigName1746875099859'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`access\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`role\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`is_organizer_role\` tinyint NOT NULL DEFAULT 0, UNIQUE INDEX \`IDX_ae4578dcaed5adff96595e6166\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`topic\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`language\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`country\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, UNIQUE INDEX \`IDX_2c5aa339240c0c3ae97fcc9dc4\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`field_dependency\` (\`id\` varchar(36) NOT NULL, \`question_id\` varchar(36) NULL, \`dependent_question_id\` varchar(36) NULL, \`choice_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`choice\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`fieldId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`form_section\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`eventId\` varchar(36) NULL, UNIQUE INDEX \`REL_ed02fe1d1e0363b207a5472ca2\` (\`eventId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`field\` (\`id\` varchar(36) NOT NULL, \`title\` varchar(255) NOT NULL, \`description\` varchar(255) NULL, \`type\` enum ('Text', 'Multiple Choice', 'Checkbox') NOT NULL DEFAULT 'Text', \`required\` tinyint NOT NULL, \`relatedFieldId\` varchar(36) NULL, \`formSectionId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`type_participant\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`eventId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`application_relation\` (\`id\` varchar(36) NOT NULL, \`FirstName\` varchar(255) NULL, \`LastName\` varchar(255) NULL, \`Function\` varchar(255) NULL, \`PhoneNumber\` varchar(255) NULL, \`ProfilePicture\` varchar(255) NULL, \`OrganisationName\` varchar(255) NULL, \`OrganisationType\` varchar(255) NULL, \`OrganisationPhoneNumber\` varchar(255) NULL, \`OrganisationDescription\` varchar(255) NULL, \`OrganisationWebsite\` varchar(255) NULL, \`OrganisationLogo\` varchar(255) NULL, \`OrganisationProduct\` varchar(255) NULL, \`Linkedin\` varchar(255) NULL, \`Facebook\` varchar(255) NULL, \`X\` varchar(255) NULL, \`Instagram\` varchar(255) NULL, \`pays\` varchar(255) NULL, \`Departement\` varchar(255) NULL, \`Ville\` varchar(255) NULL, \`CodePostal\` int NULL, \`Adresse\` varchar(255) NULL, \`currentStep\` int NULL, \`DateInscription\` datetime NULL, \`Questions\` varchar(255) NULL, \`userId\` varchar(36) NULL, \`eventId\` varchar(36) NULL, \`participationTypeId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`location\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`eventId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`meeting\` (\`id\` varchar(36) NOT NULL, \`status\` enum ('En attente', 'Confirmé', 'Annulé', 'Terminé', 'En cours') NOT NULL DEFAULT 'En attente', \`hostId\` varchar(36) NULL, \`gestId\` varchar(36) NULL, \`intervalId\` varchar(36) NULL, \`sessionId\` varchar(36) NULL, \`locationId\` varchar(36) NULL, \`eventId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`interval\` (\`id\` varchar(36) NOT NULL, \`start\` datetime NULL, \`end\` datetime NULL, \`sessionId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`session\` (\`id\` varchar(36) NOT NULL, \`startTime\` datetime NOT NULL, \`endTime\` datetime NOT NULL, \`eventId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`section_type\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`image_url\` (\`id\` varchar(36) NOT NULL, \`url\` varchar(255) NOT NULL, \`section_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`section\` (\`id\` varchar(36) NOT NULL, \`title\` varchar(255) NULL, \`description\` text NULL, \`website_tab_id\` varchar(36) NULL, \`section_type_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`website_tab\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NULL, \`eventId\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`event\` (\`id\` varchar(36) NOT NULL, \`path\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` varchar(255) NULL, \`startDate\` datetime NOT NULL, \`endDate\` datetime NOT NULL, \`timezone\` varchar(255) NULL, \`registrations\` int NOT NULL, \`state\` varchar(255) NOT NULL, \`paid\` tinyint NOT NULL, \`price\` int NOT NULL, \`type\` varchar(255) NOT NULL, \`id_country\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_role\` (\`id\` varchar(36) NOT NULL, \`userId\` varchar(36) NULL, \`roleId\` varchar(36) NULL, \`eventId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`token\` (\`id\` varchar(36) NOT NULL, \`token\` varchar(255) NOT NULL, \`validity\` varchar(255) NOT NULL, \`is_expired\` tinyint NOT NULL DEFAULT 0, \`expired_date\` datetime NOT NULL, \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, \`id_user\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user\` (\`id\` varchar(36) NOT NULL, \`email\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`is_organizer\` tinyint NOT NULL DEFAULT 0, \`Pays\` varchar(255) NULL, \`createdAt\` datetime NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`event_topic\` (\`id_event\` varchar(255) NOT NULL, \`id_topic\` varchar(255) NOT NULL, PRIMARY KEY (\`id_event\`, \`id_topic\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`event_language\` (\`id_event\` varchar(255) NOT NULL, \`id_language\` varchar(255) NOT NULL, PRIMARY KEY (\`id_event\`, \`id_language\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`mailer_history\` (\`id\` varchar(36) NOT NULL, \`from\` varchar(255) NULL, \`participantTypes\` text NULL, \`recipients\` text NOT NULL, \`eventId\` varchar(255) NULL, \`subject\` text NOT NULL, \`html\` text NOT NULL, \`text\` text NULL, \`status\` varchar(50) NOT NULL DEFAULT 'pending', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`sendAt\` timestamp NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`role_accesses_access\` (\`roleId\` varchar(36) NOT NULL, \`accessId\` varchar(36) NOT NULL, INDEX \`IDX_9ff787dad07d47363576d5fb9b\` (\`roleId\`), INDEX \`IDX_d6e843cf738eed733886acb343\` (\`accessId\`), PRIMARY KEY (\`roleId\`, \`accessId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_type_participant\` (\`type_participant_id\` varchar(36) NOT NULL, \`user_id\` varchar(36) NOT NULL, INDEX \`IDX_f017c57fab28e79a822c0d803a\` (\`type_participant_id\`), INDEX \`IDX_0a0c537cfb07fc6b24073569fe\` (\`user_id\`), PRIMARY KEY (\`type_participant_id\`, \`user_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`type_participant_relations\` (\`type_participant_id\` varchar(36) NOT NULL, \`related_type_participant_id\` varchar(36) NOT NULL, INDEX \`IDX_eaf79ebcc0872c22951032d29e\` (\`type_participant_id\`), INDEX \`IDX_e25d9591f99b5f396a07863dfb\` (\`related_type_participant_id\`), PRIMARY KEY (\`type_participant_id\`, \`related_type_participant_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`field_participant_type\` (\`type_participant_id\` varchar(36) NOT NULL, \`field_id\` varchar(36) NOT NULL, INDEX \`IDX_1486e5ed38d82570ffb4afef53\` (\`type_participant_id\`), INDEX \`IDX_57f27c78522c67e7b7718af8d3\` (\`field_id\`), PRIMARY KEY (\`type_participant_id\`, \`field_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`event_topic\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`event_topic\` ADD PRIMARY KEY (\`id_topic\`)`);
        await queryRunner.query(`ALTER TABLE \`event_topic\` DROP COLUMN \`id_event\``);
        await queryRunner.query(`ALTER TABLE \`event_topic\` ADD \`id_event\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`event_topic\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`event_topic\` ADD PRIMARY KEY (\`id_topic\`, \`id_event\`)`);
        await queryRunner.query(`ALTER TABLE \`event_topic\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`event_topic\` ADD PRIMARY KEY (\`id_event\`)`);
        await queryRunner.query(`ALTER TABLE \`event_topic\` DROP COLUMN \`id_topic\``);
        await queryRunner.query(`ALTER TABLE \`event_topic\` ADD \`id_topic\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`event_topic\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`event_topic\` ADD PRIMARY KEY (\`id_event\`, \`id_topic\`)`);
        await queryRunner.query(`ALTER TABLE \`event_language\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`event_language\` ADD PRIMARY KEY (\`id_language\`)`);
        await queryRunner.query(`ALTER TABLE \`event_language\` DROP COLUMN \`id_event\``);
        await queryRunner.query(`ALTER TABLE \`event_language\` ADD \`id_event\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`event_language\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`event_language\` ADD PRIMARY KEY (\`id_language\`, \`id_event\`)`);
        await queryRunner.query(`ALTER TABLE \`event_language\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`event_language\` ADD PRIMARY KEY (\`id_event\`)`);
        await queryRunner.query(`ALTER TABLE \`event_language\` DROP COLUMN \`id_language\``);
        await queryRunner.query(`ALTER TABLE \`event_language\` ADD \`id_language\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`event_language\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`event_language\` ADD PRIMARY KEY (\`id_event\`, \`id_language\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_f7749094b22ac26e5f9d61b3f7\` ON \`event_topic\` (\`id_event\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_1160915ee9e91c7e76b4f17662\` ON \`event_topic\` (\`id_topic\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_268b5923ec3467c81210937620\` ON \`event_language\` (\`id_event\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_e27796b6f14b3901a2542868df\` ON \`event_language\` (\`id_language\`)`);
        await queryRunner.query(`ALTER TABLE \`field_dependency\` ADD CONSTRAINT \`FK_0c4e0f000d57062d36d6e1190fc\` FOREIGN KEY (\`question_id\`) REFERENCES \`field\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`field_dependency\` ADD CONSTRAINT \`FK_2bedffb1220741eadf6d60e03f2\` FOREIGN KEY (\`dependent_question_id\`) REFERENCES \`field\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`field_dependency\` ADD CONSTRAINT \`FK_2e9f709c58bf9cf044fd428a1ac\` FOREIGN KEY (\`choice_id\`) REFERENCES \`choice\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`choice\` ADD CONSTRAINT \`FK_8b4952ed2d98ecbb0e75351f56a\` FOREIGN KEY (\`fieldId\`) REFERENCES \`field\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`form_section\` ADD CONSTRAINT \`FK_ed02fe1d1e0363b207a5472ca2c\` FOREIGN KEY (\`eventId\`) REFERENCES \`event\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`field\` ADD CONSTRAINT \`FK_5c2f271d2477a86bf6b42f5ea24\` FOREIGN KEY (\`relatedFieldId\`) REFERENCES \`field\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`field\` ADD CONSTRAINT \`FK_19b7386cdd5a8da18ae1a1b5197\` FOREIGN KEY (\`formSectionId\`) REFERENCES \`form_section\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`type_participant\` ADD CONSTRAINT \`FK_ef5b8dd100a27771f5de85fdb6a\` FOREIGN KEY (\`eventId\`) REFERENCES \`event\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`application_relation\` ADD CONSTRAINT \`FK_ecdc53ce45ec2b83756f9c64eb1\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`application_relation\` ADD CONSTRAINT \`FK_258d2dd56a8b8dae0f39b0da629\` FOREIGN KEY (\`eventId\`) REFERENCES \`event\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`application_relation\` ADD CONSTRAINT \`FK_dbfd7d5f8e779a4b78ba5588263\` FOREIGN KEY (\`participationTypeId\`) REFERENCES \`type_participant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`location\` ADD CONSTRAINT \`FK_46a2c32a486792093f81a890dda\` FOREIGN KEY (\`eventId\`) REFERENCES \`event\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`meeting\` ADD CONSTRAINT \`FK_cad9f9392de84ea417ff7cce375\` FOREIGN KEY (\`hostId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`meeting\` ADD CONSTRAINT \`FK_c4f111674ffc51b2a07dd3eb9db\` FOREIGN KEY (\`gestId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`meeting\` ADD CONSTRAINT \`FK_499a7d0a2317e3c9c6ab79d60f0\` FOREIGN KEY (\`intervalId\`) REFERENCES \`interval\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`meeting\` ADD CONSTRAINT \`FK_b6c354417b96e919fe071ebfc6b\` FOREIGN KEY (\`sessionId\`) REFERENCES \`session\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`meeting\` ADD CONSTRAINT \`FK_b820a406039cd91e4ceaef5aa9d\` FOREIGN KEY (\`locationId\`) REFERENCES \`location\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`meeting\` ADD CONSTRAINT \`FK_7aa245268e5a7d1137d0fe446c4\` FOREIGN KEY (\`eventId\`) REFERENCES \`event\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`interval\` ADD CONSTRAINT \`FK_0b6b9af3f4c898060136478e708\` FOREIGN KEY (\`sessionId\`) REFERENCES \`session\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`session\` ADD CONSTRAINT \`FK_e95ba9528d42c2633427e92c11e\` FOREIGN KEY (\`eventId\`) REFERENCES \`event\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`image_url\` ADD CONSTRAINT \`FK_3b41de86a1f8e58083e3e33656b\` FOREIGN KEY (\`section_id\`) REFERENCES \`section\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`section\` ADD CONSTRAINT \`FK_e260fa204cb0ecc9a3e3b938160\` FOREIGN KEY (\`website_tab_id\`) REFERENCES \`website_tab\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`section\` ADD CONSTRAINT \`FK_dd2ebcb89d1d4cf4eed4eccb384\` FOREIGN KEY (\`section_type_id\`) REFERENCES \`section_type\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`website_tab\` ADD CONSTRAINT \`FK_8ae8ee2409572d6b0ec475840c2\` FOREIGN KEY (\`eventId\`) REFERENCES \`event\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`event\` ADD CONSTRAINT \`FK_287ce665628247c8c0be6b151e1\` FOREIGN KEY (\`id_country\`) REFERENCES \`country\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_role\` ADD CONSTRAINT \`FK_ab40a6f0cd7d3ebfcce082131fd\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_role\` ADD CONSTRAINT \`FK_dba55ed826ef26b5b22bd39409b\` FOREIGN KEY (\`roleId\`) REFERENCES \`role\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_role\` ADD CONSTRAINT \`FK_44e82ca48e80841da3e0cdbd684\` FOREIGN KEY (\`eventId\`) REFERENCES \`event\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`token\` ADD CONSTRAINT \`FK_0275c2934dae442d1deea90b429\` FOREIGN KEY (\`id_user\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`event_topic\` ADD CONSTRAINT \`FK_f7749094b22ac26e5f9d61b3f7c\` FOREIGN KEY (\`id_event\`) REFERENCES \`event\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`event_topic\` ADD CONSTRAINT \`FK_1160915ee9e91c7e76b4f176626\` FOREIGN KEY (\`id_topic\`) REFERENCES \`topic\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`event_language\` ADD CONSTRAINT \`FK_268b5923ec3467c81210937620d\` FOREIGN KEY (\`id_event\`) REFERENCES \`event\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`event_language\` ADD CONSTRAINT \`FK_e27796b6f14b3901a2542868dfb\` FOREIGN KEY (\`id_language\`) REFERENCES \`language\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`role_accesses_access\` ADD CONSTRAINT \`FK_9ff787dad07d47363576d5fb9b7\` FOREIGN KEY (\`roleId\`) REFERENCES \`role\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`role_accesses_access\` ADD CONSTRAINT \`FK_d6e843cf738eed733886acb343c\` FOREIGN KEY (\`accessId\`) REFERENCES \`access\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_type_participant\` ADD CONSTRAINT \`FK_f017c57fab28e79a822c0d803a8\` FOREIGN KEY (\`type_participant_id\`) REFERENCES \`type_participant\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`user_type_participant\` ADD CONSTRAINT \`FK_0a0c537cfb07fc6b24073569fed\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`type_participant_relations\` ADD CONSTRAINT \`FK_eaf79ebcc0872c22951032d29eb\` FOREIGN KEY (\`type_participant_id\`) REFERENCES \`type_participant\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`type_participant_relations\` ADD CONSTRAINT \`FK_e25d9591f99b5f396a07863dfba\` FOREIGN KEY (\`related_type_participant_id\`) REFERENCES \`type_participant\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`field_participant_type\` ADD CONSTRAINT \`FK_1486e5ed38d82570ffb4afef533\` FOREIGN KEY (\`type_participant_id\`) REFERENCES \`type_participant\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`field_participant_type\` ADD CONSTRAINT \`FK_57f27c78522c67e7b7718af8d30\` FOREIGN KEY (\`field_id\`) REFERENCES \`field\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`field_participant_type\` DROP FOREIGN KEY \`FK_57f27c78522c67e7b7718af8d30\``);
        await queryRunner.query(`ALTER TABLE \`field_participant_type\` DROP FOREIGN KEY \`FK_1486e5ed38d82570ffb4afef533\``);
        await queryRunner.query(`ALTER TABLE \`type_participant_relations\` DROP FOREIGN KEY \`FK_e25d9591f99b5f396a07863dfba\``);
        await queryRunner.query(`ALTER TABLE \`type_participant_relations\` DROP FOREIGN KEY \`FK_eaf79ebcc0872c22951032d29eb\``);
        await queryRunner.query(`ALTER TABLE \`user_type_participant\` DROP FOREIGN KEY \`FK_0a0c537cfb07fc6b24073569fed\``);
        await queryRunner.query(`ALTER TABLE \`user_type_participant\` DROP FOREIGN KEY \`FK_f017c57fab28e79a822c0d803a8\``);
        await queryRunner.query(`ALTER TABLE \`role_accesses_access\` DROP FOREIGN KEY \`FK_d6e843cf738eed733886acb343c\``);
        await queryRunner.query(`ALTER TABLE \`role_accesses_access\` DROP FOREIGN KEY \`FK_9ff787dad07d47363576d5fb9b7\``);
        await queryRunner.query(`ALTER TABLE \`event_language\` DROP FOREIGN KEY \`FK_e27796b6f14b3901a2542868dfb\``);
        await queryRunner.query(`ALTER TABLE \`event_language\` DROP FOREIGN KEY \`FK_268b5923ec3467c81210937620d\``);
        await queryRunner.query(`ALTER TABLE \`event_topic\` DROP FOREIGN KEY \`FK_1160915ee9e91c7e76b4f176626\``);
        await queryRunner.query(`ALTER TABLE \`event_topic\` DROP FOREIGN KEY \`FK_f7749094b22ac26e5f9d61b3f7c\``);
        await queryRunner.query(`ALTER TABLE \`token\` DROP FOREIGN KEY \`FK_0275c2934dae442d1deea90b429\``);
        await queryRunner.query(`ALTER TABLE \`user_role\` DROP FOREIGN KEY \`FK_44e82ca48e80841da3e0cdbd684\``);
        await queryRunner.query(`ALTER TABLE \`user_role\` DROP FOREIGN KEY \`FK_dba55ed826ef26b5b22bd39409b\``);
        await queryRunner.query(`ALTER TABLE \`user_role\` DROP FOREIGN KEY \`FK_ab40a6f0cd7d3ebfcce082131fd\``);
        await queryRunner.query(`ALTER TABLE \`event\` DROP FOREIGN KEY \`FK_287ce665628247c8c0be6b151e1\``);
        await queryRunner.query(`ALTER TABLE \`website_tab\` DROP FOREIGN KEY \`FK_8ae8ee2409572d6b0ec475840c2\``);
        await queryRunner.query(`ALTER TABLE \`section\` DROP FOREIGN KEY \`FK_dd2ebcb89d1d4cf4eed4eccb384\``);
        await queryRunner.query(`ALTER TABLE \`section\` DROP FOREIGN KEY \`FK_e260fa204cb0ecc9a3e3b938160\``);
        await queryRunner.query(`ALTER TABLE \`image_url\` DROP FOREIGN KEY \`FK_3b41de86a1f8e58083e3e33656b\``);
        await queryRunner.query(`ALTER TABLE \`session\` DROP FOREIGN KEY \`FK_e95ba9528d42c2633427e92c11e\``);
        await queryRunner.query(`ALTER TABLE \`interval\` DROP FOREIGN KEY \`FK_0b6b9af3f4c898060136478e708\``);
        await queryRunner.query(`ALTER TABLE \`meeting\` DROP FOREIGN KEY \`FK_7aa245268e5a7d1137d0fe446c4\``);
        await queryRunner.query(`ALTER TABLE \`meeting\` DROP FOREIGN KEY \`FK_b820a406039cd91e4ceaef5aa9d\``);
        await queryRunner.query(`ALTER TABLE \`meeting\` DROP FOREIGN KEY \`FK_b6c354417b96e919fe071ebfc6b\``);
        await queryRunner.query(`ALTER TABLE \`meeting\` DROP FOREIGN KEY \`FK_499a7d0a2317e3c9c6ab79d60f0\``);
        await queryRunner.query(`ALTER TABLE \`meeting\` DROP FOREIGN KEY \`FK_c4f111674ffc51b2a07dd3eb9db\``);
        await queryRunner.query(`ALTER TABLE \`meeting\` DROP FOREIGN KEY \`FK_cad9f9392de84ea417ff7cce375\``);
        await queryRunner.query(`ALTER TABLE \`location\` DROP FOREIGN KEY \`FK_46a2c32a486792093f81a890dda\``);
        await queryRunner.query(`ALTER TABLE \`application_relation\` DROP FOREIGN KEY \`FK_dbfd7d5f8e779a4b78ba5588263\``);
        await queryRunner.query(`ALTER TABLE \`application_relation\` DROP FOREIGN KEY \`FK_258d2dd56a8b8dae0f39b0da629\``);
        await queryRunner.query(`ALTER TABLE \`application_relation\` DROP FOREIGN KEY \`FK_ecdc53ce45ec2b83756f9c64eb1\``);
        await queryRunner.query(`ALTER TABLE \`type_participant\` DROP FOREIGN KEY \`FK_ef5b8dd100a27771f5de85fdb6a\``);
        await queryRunner.query(`ALTER TABLE \`field\` DROP FOREIGN KEY \`FK_19b7386cdd5a8da18ae1a1b5197\``);
        await queryRunner.query(`ALTER TABLE \`field\` DROP FOREIGN KEY \`FK_5c2f271d2477a86bf6b42f5ea24\``);
        await queryRunner.query(`ALTER TABLE \`form_section\` DROP FOREIGN KEY \`FK_ed02fe1d1e0363b207a5472ca2c\``);
        await queryRunner.query(`ALTER TABLE \`choice\` DROP FOREIGN KEY \`FK_8b4952ed2d98ecbb0e75351f56a\``);
        await queryRunner.query(`ALTER TABLE \`field_dependency\` DROP FOREIGN KEY \`FK_2e9f709c58bf9cf044fd428a1ac\``);
        await queryRunner.query(`ALTER TABLE \`field_dependency\` DROP FOREIGN KEY \`FK_2bedffb1220741eadf6d60e03f2\``);
        await queryRunner.query(`ALTER TABLE \`field_dependency\` DROP FOREIGN KEY \`FK_0c4e0f000d57062d36d6e1190fc\``);
        await queryRunner.query(`DROP INDEX \`IDX_e27796b6f14b3901a2542868df\` ON \`event_language\``);
        await queryRunner.query(`DROP INDEX \`IDX_268b5923ec3467c81210937620\` ON \`event_language\``);
        await queryRunner.query(`DROP INDEX \`IDX_1160915ee9e91c7e76b4f17662\` ON \`event_topic\``);
        await queryRunner.query(`DROP INDEX \`IDX_f7749094b22ac26e5f9d61b3f7\` ON \`event_topic\``);
        await queryRunner.query(`ALTER TABLE \`event_language\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`event_language\` ADD PRIMARY KEY (\`id_event\`)`);
        await queryRunner.query(`ALTER TABLE \`event_language\` DROP COLUMN \`id_language\``);
        await queryRunner.query(`ALTER TABLE \`event_language\` ADD \`id_language\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`event_language\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`event_language\` ADD PRIMARY KEY (\`id_language\`, \`id_event\`)`);
        await queryRunner.query(`ALTER TABLE \`event_language\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`event_language\` ADD PRIMARY KEY (\`id_language\`)`);
        await queryRunner.query(`ALTER TABLE \`event_language\` DROP COLUMN \`id_event\``);
        await queryRunner.query(`ALTER TABLE \`event_language\` ADD \`id_event\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`event_language\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`event_language\` ADD PRIMARY KEY (\`id_event\`, \`id_language\`)`);
        await queryRunner.query(`ALTER TABLE \`event_topic\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`event_topic\` ADD PRIMARY KEY (\`id_event\`)`);
        await queryRunner.query(`ALTER TABLE \`event_topic\` DROP COLUMN \`id_topic\``);
        await queryRunner.query(`ALTER TABLE \`event_topic\` ADD \`id_topic\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`event_topic\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`event_topic\` ADD PRIMARY KEY (\`id_topic\`, \`id_event\`)`);
        await queryRunner.query(`ALTER TABLE \`event_topic\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`event_topic\` ADD PRIMARY KEY (\`id_topic\`)`);
        await queryRunner.query(`ALTER TABLE \`event_topic\` DROP COLUMN \`id_event\``);
        await queryRunner.query(`ALTER TABLE \`event_topic\` ADD \`id_event\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`event_topic\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`event_topic\` ADD PRIMARY KEY (\`id_event\`, \`id_topic\`)`);
        await queryRunner.query(`DROP INDEX \`IDX_57f27c78522c67e7b7718af8d3\` ON \`field_participant_type\``);
        await queryRunner.query(`DROP INDEX \`IDX_1486e5ed38d82570ffb4afef53\` ON \`field_participant_type\``);
        await queryRunner.query(`DROP TABLE \`field_participant_type\``);
        await queryRunner.query(`DROP INDEX \`IDX_e25d9591f99b5f396a07863dfb\` ON \`type_participant_relations\``);
        await queryRunner.query(`DROP INDEX \`IDX_eaf79ebcc0872c22951032d29e\` ON \`type_participant_relations\``);
        await queryRunner.query(`DROP TABLE \`type_participant_relations\``);
        await queryRunner.query(`DROP INDEX \`IDX_0a0c537cfb07fc6b24073569fe\` ON \`user_type_participant\``);
        await queryRunner.query(`DROP INDEX \`IDX_f017c57fab28e79a822c0d803a\` ON \`user_type_participant\``);
        await queryRunner.query(`DROP TABLE \`user_type_participant\``);
        await queryRunner.query(`DROP INDEX \`IDX_d6e843cf738eed733886acb343\` ON \`role_accesses_access\``);
        await queryRunner.query(`DROP INDEX \`IDX_9ff787dad07d47363576d5fb9b\` ON \`role_accesses_access\``);
        await queryRunner.query(`DROP TABLE \`role_accesses_access\``);
        await queryRunner.query(`DROP TABLE \`mailer_history\``);
        await queryRunner.query(`DROP TABLE \`event_language\``);
        await queryRunner.query(`DROP TABLE \`event_topic\``);
        await queryRunner.query(`DROP TABLE \`user\``);
        await queryRunner.query(`DROP TABLE \`token\``);
        await queryRunner.query(`DROP TABLE \`user_role\``);
        await queryRunner.query(`DROP TABLE \`event\``);
        await queryRunner.query(`DROP TABLE \`website_tab\``);
        await queryRunner.query(`DROP TABLE \`section\``);
        await queryRunner.query(`DROP TABLE \`image_url\``);
        await queryRunner.query(`DROP TABLE \`section_type\``);
        await queryRunner.query(`DROP TABLE \`session\``);
        await queryRunner.query(`DROP TABLE \`interval\``);
        await queryRunner.query(`DROP TABLE \`meeting\``);
        await queryRunner.query(`DROP TABLE \`location\``);
        await queryRunner.query(`DROP TABLE \`application_relation\``);
        await queryRunner.query(`DROP TABLE \`type_participant\``);
        await queryRunner.query(`DROP TABLE \`field\``);
        await queryRunner.query(`DROP INDEX \`REL_ed02fe1d1e0363b207a5472ca2\` ON \`form_section\``);
        await queryRunner.query(`DROP TABLE \`form_section\``);
        await queryRunner.query(`DROP TABLE \`choice\``);
        await queryRunner.query(`DROP TABLE \`field_dependency\``);
        await queryRunner.query(`DROP INDEX \`IDX_2c5aa339240c0c3ae97fcc9dc4\` ON \`country\``);
        await queryRunner.query(`DROP TABLE \`country\``);
        await queryRunner.query(`DROP TABLE \`language\``);
        await queryRunner.query(`DROP TABLE \`topic\``);
        await queryRunner.query(`DROP INDEX \`IDX_ae4578dcaed5adff96595e6166\` ON \`role\``);
        await queryRunner.query(`DROP TABLE \`role\``);
        await queryRunner.query(`DROP TABLE \`access\``);
    }

}
